const $=id=>document.getElementById(id); let currentFile=null, openFiles={}, eventSource=null;
async function j(url,opt){const r=await fetch(url,opt);const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={error:t}}if(!r.ok)throw new Error(d.detail||d.error||t);return d}
function esc(s=''){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function setView(name){document.querySelectorAll('.activity button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelectorAll('.sideview').forEach(v=>v.classList.add('hidden'));$(name+'View').classList.remove('hidden');$('viewTitle').textContent=name.toUpperCase();if(name==='tasks')loadTasks();if(name==='models')loadModelHealth();if(name==='security')loadSecurity();if(name==='source')loadGit()}
document.querySelectorAll('.activity button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('refreshBtn').onclick=refreshAll;
async function loadTree(){let d=await j('/api/tree');$('tree').innerHTML='';renderTree(d.tree,$('tree'))}
function renderTree(items,parent){items.forEach(x=>{let e=document.createElement('div');e.className='node '+x.type;e.textContent=(x.type==='dir'?'▸ ':'')+x.name;e.title=x.path;parent.appendChild(e);if(x.type==='dir'){let c=document.createElement('div');c.className='children';parent.appendChild(c);e.onclick=()=>{c.classList.toggle('hidden');e.textContent=(c.classList.contains('hidden')?'▸ ':'▾ ')+x.name};renderTree(x.children||[],c)}else e.onclick=()=>openFile(x.path)})}
async function openFile(path){let d=await j('/api/file?path='+encodeURIComponent(path));openFiles[path]=d.content;currentFile=path;renderTabs();renderEditor(path,d.content)}
function renderTabs(){let t=$('tabs');t.innerHTML='';Object.keys(openFiles).forEach(path=>{let e=document.createElement('div');e.textContent=path.split('/').pop();e.title=path;e.classList.toggle('active',path===currentFile);e.onclick=()=>{currentFile=path;renderTabs();renderEditor(path,openFiles[path])};t.appendChild(e)});if(!Object.keys(openFiles).length){let e=document.createElement('div');e.className='welcome-tab active';e.textContent='Welcome';t.appendChild(e)}}
function lineNums(v){return Array.from({length:(v.match(/\n/g)||[]).length+1},(_,i)=>i+1).join('\n')}
function renderEditor(path,content){$('editorArea').innerHTML='<div class="code-shell"><pre class="line-numbers" id="lineNumbers"></pre><textarea class="code" id="code"></textarea></div>';$('code').value=content;$('lineNumbers').textContent=lineNums(content);$('code').oninput=()=>{$('lineNumbers').textContent=lineNums($('code').value);openFiles[path]=$('code').value};$('code').onscroll=()=>$('lineNumbers').scrollTop=$('code').scrollTop;$('code').onkeydown=async e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();await saveCurrent()}if(e.key==='Tab'){e.preventDefault();let a=e.target.selectionStart,b=e.target.selectionEnd,v=e.target.value;e.target.value=v.slice(0,a)+'    '+v.slice(b);e.target.selectionStart=e.target.selectionEnd=a+4;e.target.oninput()}}}
async function saveCurrent(){if(!currentFile)return;await j('/api/file',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:currentFile,content:$('code').value})});openFiles[currentFile]=$('code').value;appendOutput('Saved '+currentFile);await loadGit()}
async function loadModels(){let ms=await j('/api/models');let cur=$('model').value;$('model').innerHTML=ms.map(m=>`<option value="${m.id}">${m.vendor} · ${m.id}</option>`).join('');if(cur)$('model').value=cur}
async function loadModelHealth(){try{let hs=await j('/api/models/health');let on=hs.filter(x=>x.online).length;$('modelHealth').textContent=`● ${on}/${hs.length} models online`;$('modelHealth').style.color=on?'#73c991':'#f48771';$('modelsPanel').innerHTML=hs.map(m=>`<div class="model-card"><span class="dot ${m.online?'online':''}"></span><b>${esc(m.id)}</b><br><small>${esc(m.vendor)} · ${m.estimated_vram_gb||'?'} GB VRAM · ${m.online?'online':'offline'}</small></div>`).join('')}catch(e){$('modelHealth').textContent='● model health unavailable'}}
async function loadTasks(){let ts=await j('/api/tasks');$('tasks').innerHTML=ts.map(t=>`<div class="task-card" onclick="showTask('${t.id}')"><b>${esc(t.status)}</b><small>${esc(t.id)} · ${esc(t.model||'')}</small><div>${esc((t.prompt||'').slice(0,95))}</div></div>`).join('')||'<div class="task-card">No tasks yet</div>'}
async function showTask(id){let t=await j('/api/tasks/'+id);setPanel('output');$('outputPanel').textContent=JSON.stringify(t,null,2)}
function addMsg(role,text){let d=document.createElement('div');d.className='msg '+role;d.textContent=text;$('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight}
function focusChat(){$('input').focus()}
async function sendChat(){let text=$('input').value.trim();if(!text)return;$('input').value='';addMsg('user',text);try{let d=await j('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,model:$('model').value})});addMsg('agent',d.response);updateTelemetry(d.telemetry)}catch(e){addMsg('error',e.message)}}
async function runTask(){let text=$('input').value.trim();if(!text)return;$('input').value='';addMsg('user',text);try{let d=await j('/api/task/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,model:$('model').value,allow_network:$('network').checked})});$('taskStatus').textContent='Task '+d.task_id+' running';$('liveTask').classList.remove('hidden');$('liveTask').textContent='Starting '+d.task_id+'…';streamTask(d.task_id)}catch(e){addMsg('error',e.message)}}
function streamTask(id){if(eventSource)eventSource.close();eventSource=new EventSource('/api/tasks/'+id+'/stream');let lines=[];['plan','agent_action','tool_result','final_review','model_error'].forEach(ev=>eventSource.addEventListener(ev,e=>{let x=JSON.parse(e.data);let short=ev.toUpperCase()+': '+JSON.stringify(x.payload).slice(0,450);lines.push(short);$('liveTask').textContent=lines.slice(-8).join('\n');appendOutput(short)}));eventSource.addEventListener('done',async e=>{let x=JSON.parse(e.data);$('taskStatus').textContent='Task '+id+' '+x.status;eventSource.close();addMsg('agent','Task '+id+' finished with status: '+x.status);await Promise.all([loadTree(),loadTasks(),loadGit(),showDiff(),loadTelemetry()])})}
async function runTerminal(){let cmd=$('terminalInput').value.trim();if(!cmd)return;$('terminalInput').value='';$('terminalOut').textContent+='\n$ '+cmd+'\n';try{let d=await j('/api/terminal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:cmd,allow_network:$('network').checked})});$('terminalOut').textContent+=d.result+'\n'}catch(e){$('terminalOut').textContent+='ERROR: '+e.message+'\n'}$('terminalOut').scrollTop=$('terminalOut').scrollHeight}
$('terminalInput').addEventListener('keydown',e=>{if(e.key==='Enter')runTerminal()});
function setPanel(name){document.querySelectorAll('.panel-tabs button[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));document.querySelectorAll('.panel-content').forEach(p=>p.classList.add('hidden'));$(name+'Panel').classList.remove('hidden')}
document.querySelectorAll('.panel-tabs button[data-panel]').forEach(b=>b.onclick=()=>{setPanel(b.dataset.panel);if(b.dataset.panel==='diff')showDiff()});$('panelToggle').onclick=()=>{$('bottomPanel').classList.toggle('hidden')};
function appendOutput(t){$('outputPanel').textContent+=( $('outputPanel').textContent?'\n':'')+t}
async function showDiff(){try{let d=await j('/api/git/diff');$('diffPanel').textContent=d.stdout||d.stderr||'No working-tree diff.';setPanel('diff')}catch(e){$('diffPanel').textContent=e.message}}
async function loadGit(){try{let d=await j('/api/git/status');$('gitPanel').textContent=d.stdout||'Working tree clean';$('branchStatus').textContent='⑂ '+(d.stdout?'changes':'clean')}catch(e){$('gitPanel').textContent=e.message}}
async function runQuality(){try{let d=await j('/api/quality');$('problemsPanel').textContent=JSON.stringify(d,null,2);$('problemsPanel').className='panel-content '+(d.ok?'problems-good':'problems-bad');setPanel('problems');appendOutput('Quality gate: '+(d.ok?'PASS':'FAIL'))}catch(e){$('problemsPanel').textContent=e.message;setPanel('problems')}}
async function loadSecurity(){try{let d=await j('/api/security');$('securityPanel').innerHTML=d.findings.length?d.findings.map(f=>`<div class="finding"><b>${esc(f.rule)}</b><br><small>${esc(f.file)}:${f.line}</small></div>`).join(''):'<div class="finding">No secret patterns found.</div>'}catch(e){$('securityPanel').textContent=e.message}}
async function loadTelemetry(){try{let d=await j('/api/telemetry');updateTelemetry(d)}catch{}}
function updateTelemetry(d={}){$('telemetryStatus').textContent=(d.estimated_local_tokens||0).toLocaleString()+' local tokens · '+(d.estimated_cloud_tokens_avoided||0).toLocaleString()+' cloud tokens avoided'}
async function refreshAll(){await Promise.all([loadTree(),loadModels(),loadModelHealth(),loadTasks(),loadGit(),loadTelemetry()])}
refreshAll();
